server:
  port: 8088

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 7757
    url: jdbc:mysql://localhost:3306/doubao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.douyuehan.doubao: info
